// Generated by scripts/gen-public-api.mjs from public-queries.json. Do not edit: run pnpm gen:api.

export type Locale = 'zh' | 'ja' | 'en'

/** A multilingual text: its value in each language that has one (the others fall back, 16 section 1). */
export type LocalizedText = Partial<Record<Locale, string>>

/** A file's id: GET /api/public/files/{id}[/{variant}]. */
export type FileId = string

/** The public templates: parameters (p.<name>), rows, outer filters and sorts. */
export interface PublicQueries {
  /** The photographs and videos of the people from a place, each with its published story (map) */
  "culture.public.location_media": {
    params: {
      location: string
    }
    row: {
      alt: LocalizedText | null
      displayName: string | null
      imageFileId: FileId | null
      itemId: string | null
      kind: string | null
      participantSlug: string | null
      storyDate: string | null
      storySlug: string | null
      storyTitle: LocalizedText | null
      videoId: string | null
      videoProvider: "YOUTUBE" | "VIMEO" | null
    }
    filters: "kind"
    sorts: "storyDate" | "itemId"
  }
  /** The themes of the published stories in which someone from a place has a perspective (map) */
  "culture.public.location_themes": {
    params: {
      location: string
    }
    row: {
      icon: string | null
      slug: string | null
      sortOrder: number | null
      storyCount: number | null
      themeId: string | null
      title: LocalizedText | null
    }
    filters: never
    sorts: "sortOrder" | "storyCount"
  }
  /** Places with how many participants and published stories each has (map, filters) */
  "culture.public.locations": {
    params: Record<string, never>
    row: {
      countryCode: string | null
      latitude: number | null
      locationId: string | null
      longitude: number | null
      name: LocalizedText | null
      participantCount: number | null
      placeLabel: LocalizedText | null
      slug: string | null
      sortOrder: number | null
      storyCount: number | null
    }
    filters: "slug" | "countryCode"
    sorts: "sortOrder" | "slug"
  }
  /** Participants' cards, optionally of some places */
  "culture.public.people": {
    params: {
      location?: readonly (string)[]
    }
    row: {
      countryCode: string | null
      displayName: string | null
      interests: LocalizedText | null
      locationName: LocalizedText | null
      locationSlug: string | null
      participantId: string | null
      portraitAlt: LocalizedText | null
      portraitFileId: FileId | null
      shortBio: LocalizedText | null
      slug: string | null
      sortOrder: number | null
    }
    filters: "locationSlug"
    sorts: "sortOrder" | "displayName"
  }
  /** A participant's page, header and texts */
  "culture.public.person": {
    params: {
      slug: string
    }
    row: {
      bio: LocalizedText | null
      countryCode: string | null
      displayName: string | null
      interests: LocalizedText | null
      languages: string | null
      locationName: LocalizedText | null
      locationSlug: string | null
      participantId: string | null
      perspective: LocalizedText | null
      placeLabel: LocalizedText | null
      portraitAlt: LocalizedText | null
      portraitFileId: FileId | null
      reflection: LocalizedText | null
      shortBio: LocalizedText | null
      slug: string | null
    }
    filters: never
    sorts: never
  }
  /** The published stories a participant has a perspective in */
  "culture.public.person_stories": {
    params: {
      slug: string
    }
    row: {
      mediaType: string | null
      publishedTime: string | null
      slug: string | null
      storyDate: string | null
      storyId: string | null
      summary: LocalizedText | null
      thumbnailAlt: LocalizedText | null
      thumbnailFileId: FileId | null
      title: LocalizedText | null
    }
    filters: "mediaType"
    sorts: "storyDate" | "publishedTime"
  }
  /** The themes of the published stories a participant has a perspective in */
  "culture.public.person_themes": {
    params: {
      slug: string
    }
    row: {
      icon: string | null
      slug: string | null
      sortOrder: number | null
      storyCount: number | null
      themeId: string | null
      title: LocalizedText | null
    }
    filters: never
    sorts: "sortOrder" | "storyCount"
  }
  /** A teaching resource's page, with its steps to read on the page and its PDF */
  "culture.public.resource": {
    params: {
      slug: string
    }
    row: {
      activityType: string | null
      ageGroup: string | null
      body: LocalizedText | null
      description: LocalizedText | null
      durationMinutes: number | null
      pdfFileId: FileId | null
      resourceId: string | null
      slug: string | null
      title: LocalizedText | null
    }
    filters: never
    sorts: never
  }
  /** The published stories a teaching resource works with */
  "culture.public.resource_stories": {
    params: {
      slug: string
    }
    row: {
      mediaType: string | null
      slug: string | null
      storyDate: string | null
      storyId: string | null
      summary: LocalizedText | null
      thumbnailAlt: LocalizedText | null
      thumbnailFileId: FileId | null
      title: LocalizedText | null
    }
    filters: never
    sorts: "storyDate" | "slug"
  }
  /** Teaching resources, optionally of some activity types and age groups */
  "culture.public.resources": {
    params: {
      activityType?: readonly (string)[]
      ageGroup?: readonly (string)[]
    }
    row: {
      activityType: string | null
      ageGroup: string | null
      description: LocalizedText | null
      durationMinutes: number | null
      pdfFileId: FileId | null
      resourceId: string | null
      slug: string | null
      sortOrder: number | null
      title: LocalizedText | null
    }
    filters: "activityType" | "ageGroup" | "durationMinutes"
    sorts: "sortOrder" | "durationMinutes" | "slug"
  }
  /** Stories, participants, themes and resources whose texts in any language contain the words */
  "culture.public.search": {
    params: {
      q: string
    }
    row: {
      imageFileId: FileId | null
      kind: string | null
      name: string | null
      slug: string | null
      summary: LocalizedText | null
      title: LocalizedText | null
    }
    filters: "kind"
    sorts: "kind" | "slug"
  }
  /** Texts of the fixed pages (home, method, about), by key */
  "culture.public.site_blocks": {
    params: {
      keys?: readonly (string)[]
    }
    row: {
      blockKey: string | null
      body: LocalizedText | null
    }
    filters: "blockKey"
    sorts: "blockKey"
  }
  /** The story archive, filtered by place (of the people in it), theme and media type, and searched */
  "culture.public.stories": {
    params: {
      featured?: boolean
      location?: readonly (string)[]
      mediaType?: readonly (string)[]
      q?: string
      theme?: readonly (string)[]
    }
    row: {
      featured: boolean | null
      locationSlugs: string | null
      mediaType: string | null
      publishedTime: string | null
      slug: string | null
      storyDate: string | null
      storyId: string | null
      summary: LocalizedText | null
      thumbnailAlt: LocalizedText | null
      thumbnailFileId: FileId | null
      title: LocalizedText | null
    }
    filters: "mediaType" | "featured"
    sorts: "storyDate" | "publishedTime" | "slug"
  }
  /** A story page's header, player, texts and the three reflection questions */
  "culture.public.story": {
    params: {
      slug: string
    }
    row: {
      about: LocalizedText | null
      body: LocalizedText | null
      mediaType: string | null
      publishedTime: string | null
      reflectionAssumed: LocalizedText | null
      reflectionLearned: LocalizedText | null
      reflectionSurprised: LocalizedText | null
      slug: string | null
      storyDate: string | null
      storyId: string | null
      summary: LocalizedText | null
      thumbnailAlt: LocalizedText | null
      thumbnailFileId: FileId | null
      title: LocalizedText | null
      transcript: LocalizedText | null
      videoId: string | null
      videoProvider: "YOUTUBE" | "VIMEO" | null
    }
    filters: never
    sorts: never
  }
  /** The photos and audio of a published story, its own and those of its shown perspectives */
  "culture.public.story_media": {
    params: {
      slug: string
    }
    row: {
      alt: LocalizedText | null
      audioFileId: FileId | null
      caption: LocalizedText | null
      contributionId: string | null
      credit: string | null
      imageFileId: FileId | null
      kind: "PHOTO" | "AUDIO" | null
      mediaItemId: string | null
      sortOrder: number | null
    }
    filters: "kind" | "contributionId"
    sorts: "sortOrder"
  }
  /** The perspectives of a published story, each with its participant and place */
  "culture.public.story_perspectives": {
    params: {
      slug: string
    }
    row: {
      audioFileId: FileId | null
      contributionId: string | null
      countryCode: string | null
      displayName: string | null
      heading: LocalizedText | null
      locationName: LocalizedText | null
      locationSlug: string | null
      participantId: string | null
      participantSlug: string | null
      portraitAlt: LocalizedText | null
      portraitFileId: FileId | null
      sortOrder: number | null
      text: LocalizedText | null
      transcript: LocalizedText | null
      videoId: string | null
      videoProvider: "YOUTUBE" | "VIMEO" | null
    }
    filters: never
    sorts: "sortOrder"
  }
  /** The themes of a published story */
  "culture.public.story_themes": {
    params: {
      slug: string
    }
    row: {
      icon: string | null
      slug: string | null
      sortOrder: number | null
      themeId: string | null
      title: LocalizedText | null
    }
    filters: never
    sorts: "sortOrder"
  }
  /** A theme page's header, its anthropological question and introduction */
  "culture.public.theme": {
    params: {
      slug: string
    }
    row: {
      icon: string | null
      intro: LocalizedText | null
      question: LocalizedText | null
      slug: string | null
      themeId: string | null
      title: LocalizedText | null
    }
    filters: never
    sorts: never
  }
  /** Every perspective in the published stories of a theme, place by place, to compare answers to its question */
  "culture.public.theme_perspectives": {
    params: {
      slug: string
    }
    row: {
      audioFileId: FileId | null
      contributionId: string | null
      countryCode: string | null
      displayName: string | null
      heading: LocalizedText | null
      locationName: LocalizedText | null
      locationSlug: string | null
      locationSortOrder: number | null
      mediaType: string | null
      participantId: string | null
      participantSlug: string | null
      portraitAlt: LocalizedText | null
      portraitFileId: FileId | null
      sortOrder: number | null
      storyId: string | null
      storySlug: string | null
      storyTitle: LocalizedText | null
      text: LocalizedText | null
      thumbnailAlt: LocalizedText | null
      thumbnailFileId: FileId | null
      transcript: LocalizedText | null
      videoId: string | null
      videoProvider: "YOUTUBE" | "VIMEO" | null
    }
    filters: "locationSlug" | "mediaType"
    sorts: "locationSortOrder" | "locationSlug" | "sortOrder"
  }
  /** Themes with how many published stories and places answer each */
  "culture.public.themes": {
    params: Record<string, never>
    row: {
      icon: string | null
      locationCount: number | null
      question: LocalizedText | null
      slug: string | null
      sortOrder: number | null
      storyCount: number | null
      themeId: string | null
      title: LocalizedText | null
    }
    filters: never
    sorts: "sortOrder" | "slug"
  }
}

export type PublicQueryId = keyof PublicQueries
export type QueryParams<Q extends PublicQueryId> = PublicQueries[Q]['params']
export type QueryRow<Q extends PublicQueryId> = PublicQueries[Q]['row']
export type QueryFilter<Q extends PublicQueryId> = PublicQueries[Q]['filters']
export type QuerySort<Q extends PublicQueryId> = PublicQueries[Q]['sorts']

/** A page of a public template: GET /api/public/queries/{id}. */
export interface QueryPage<Q extends PublicQueryId> {
  items: QueryRow<Q>[]
  total: number | null
  offset: number
  limit: number
}

/** How long responses may be cached (seconds), per template. */
export const cacheSeconds: Record<PublicQueryId, number> = {
  "culture.public.location_media": 60,
  "culture.public.location_themes": 60,
  "culture.public.locations": 60,
  "culture.public.people": 60,
  "culture.public.person": 60,
  "culture.public.person_stories": 60,
  "culture.public.person_themes": 60,
  "culture.public.resource": 60,
  "culture.public.resource_stories": 60,
  "culture.public.resources": 60,
  "culture.public.search": 60,
  "culture.public.site_blocks": 60,
  "culture.public.stories": 60,
  "culture.public.story": 60,
  "culture.public.story_media": 60,
  "culture.public.story_perspectives": 60,
  "culture.public.story_themes": 60,
  "culture.public.theme": 60,
  "culture.public.theme_perspectives": 60,
  "culture.public.themes": 60,
}
